# Generated by Django 2.2.6 on 2019-11-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMainTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SubSubTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='sub',
            name='ingrediant',
        ),
        migrations.AddField(
            model_name='sub',
            name='addedtoppings',
            field=models.ManyToManyField(blank=True, related_name='sub', to='orders.SubSubTopping'),
        ),
        migrations.AddField(
            model_name='sub',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='sub', to='orders.SubMainTopping'),
        ),
    ]
