# Generated by Django 2.2.6 on 2019-11-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
